routes/admin.php
Route::match(['get', 'post'],'/service_category_questions', 'Admin@Categoryquestions')->middleware('Login');
Route::match(['get', 'post'],'/service_category_image', 'Admin@Categoryimage')->middleware('Login');
Route::match(['get', 'post'],'/get_image', 'Admin@Getimage')->middleware('Login');
Route::match(['get', 'post'],'/pages', 'Admin\FrontendController@pages')->middleware('Login');
Route::match(['get', 'post'],'/blog', 'Admin\AdviceController@blog')->middleware('Login');
Route::get('/customers', 'Admin\ProductController@customers')->middleware('Login');
Route::post('/change-rfr', 'Admin@changeRfr')->middleware('Login');
Route::match(['get', 'post'],'/coupons', 'Admin\ProductController@coupons')->middleware('Login');
Route::match(['get', 'post'],'/postcodes', 'Admin\SettingsController@postcodes')->middleware('Login');
Route::match(['get', 'post'],'/shipping', 'Admin\SettingsController@shipping')->middleware('Login');
Route::match(['get', 'post'],'/flat', 'Admin\SettingsController@flat')->middleware('Login');
Route::match(['get', 'post'],'/units', 'Admin\ProductController@units')->middleware('Login');
Route::match(['get', 'post'],'/reviews', 'Admin\ProductController@reviews')->middleware('Login');
Route::match(['get', 'post'],'/photo-reviews', 'Admin\DesignController@photoreviews')->middleware('Login');
Route::match(['get', 'post'],'/layout_reviews', 'Admin\DesignController@layout_reviews')->middleware('Login');
Route::match(['get', 'post'],'/orders', 'Admin\RetailController@orders')->middleware('Login');
Route::get('/stats', 'Admin\RetailController@stats')->middleware('Login');
Route::match(['get', 'post'],'/tracking', 'Admin\MarketingController@tracking')->middleware('Login');
Route::match(['get', 'post'],'/newsletter', 'Admin\MarketingController@newsletter')->middleware('Login');
Route::get('/referrers', 'Admin\VisitorController@referrers')->middleware('Login');
Route::get('/os', 'Admin\VisitorController@os')->middleware('Login');
Route::get('/browsers', 'Admin\VisitorController@browsers')->middleware('Login');
Route::match(['get', 'post'],'/payment', 'Admin\SettingsController@payment')->middleware('Login');
Route::match(['get', 'post'],'/currency', 'Admin\SettingsController@currency')->middleware('Login');
Route::match(['get', 'post'],'/settings', 'Admin\SettingsController@settings')->middleware('Login');
Route::match(['get', 'post'],'/theme', 'Admin\SettingsController@theme')->middleware('Login');
Route::match(['get', 'post'],'/lang', 'Admin\SettingsController@lang')->middleware('Login');
Route::get('/tokens', 'Admin\SettingsController@tokens')->middleware('Login');
Route::get('/export', 'Admin\SettingsController@export')->middleware('Login');
Route::match(['get', 'post'],'/slider', 'Admin\CustomizationController@slider')->middleware('Login');
Route::match(['get', 'post'],'/editor', 'Admin\CustomizationController@editor')->middleware('Login');
Route::match(['get', 'post'],'/templates', 'Admin\CustomizationController@templates')->middleware('Login');
Route::match(['get', 'post'],'/builder', 'Admin\CustomizationController@builder')->middleware('Login');
Route::match(['get', 'post'],'/menu', 'Admin\CustomizationController@menu')->middleware('Login');
Route::match(['get', 'post'],'/bottom', 'Admin\CustomizationController@bottom')->middleware('Login');
Route::match(['get', 'post'],'/fields', 'Admin@fields')->middleware('Login');
Route::match(['get', 'post'],'/support', 'Admin\AdministrationController@support')->middleware('Login');
Route::match(['get', 'post'],'/administrators', 'Admin\AdministrationController@administrators')->middleware('Login');
Route::match(['get', 'post'],'/profile', 'Admin\AdministrationController@profile')->middleware('Login');
Route::match(['get', 'post'],'/layout_addon', 'Admin\DesignController@layout_addon')->middleware('Login');
Route::match(['get', 'post'],'/layout-plans/add-questions/{slug}', 'Admin@layout_plan_questions')->middleware('Login');
Route::match(['get', 'post'],'/layout-plans/layout_plan_addon/{slug}', 'Admin@layout_plan_addon')->middleware('Login');
Route::match(['get', 'post'],'/amminities', 'Admin\DesignController@amminities')->middleware('Login');
Route::match(['get', 'post'],'/image_likes', 'Admin\DesignController@image_likes')->middleware('Login');
Route::match(['get', 'post'],'/image_inspirations', 'Admin\DesignController@image_inspirations')->middleware('Login');
Route::match(['get', 'post'],'/plan_orders', 'Admin\DesignController@plan_orders')->middleware('Login');
Route::get('/layout-plans/delete/{slug}/{que_id}', 'Admin@layout_plan_delete_question')->middleware('Login');
Route::get('/layout-plans/delete/{slug}/{addon_id}', 'Admin@layout_plan_addoon_delete')->middleware('Login');
Route::post('/get-variant', 'Admin@getVariant')->middleware('Login');
Route::post('/get-variant-data', 'Admin@getVariantData')->middleware('Login');
Route::post('/get-discount', 'Admin@getDiscount')->middleware('Login');
Route::match(['get', 'post'],'/advices_faq', 'Admin\AdviceController@advicesFaq')->middleware('Login');
Route::match(['get', 'post'],'/advices_reviews', 'Admin\AdviceController@advices_reviews')->middleware('Login');
Route::match(['get', 'post'],'/advices_category', 'Admin\AdviceController@advices_category')->middleware('Login');
Route::match(['get', 'post'],'/best-for-cat', 'Admin\ProductController@BestForCat')->middleware('Login');
Route::match(['get', 'post'],'/services_reviews', 'Admin@services_reviews')->middleware('Login');
Route::match(['get', 'post'],'/product-type', 'Admin\ProductController@productType')->middleware('Login');
Route::match(['get', 'post'],'/filters', 'Admin\ProductController@filters')->middleware('Login');
Route::match(['get', 'post'],'/best-for-layout', 'Admin\DesignController@BestForLayout')->middleware('Login');
Route::match(['get', 'post'],'/design-cat-banner', 'Admin\DesignController@DesignCatBanner')->middleware('Login');
Route::match(['get', 'post'],'/best-for-photo', 'Admin\DesignController@BestForPhoto')->middleware('Login');
Route::match(['get', 'post'],'/length', 'Admin@Length')->middleware('Login');
Route::match(['get', 'post'],'/size', 'Admin\ProductController@Size')->middleware('Login');
Route::match(['get', 'post'],'/sizes_group', 'Admin\ProductController@SizesGroup')->middleware('Login');
Route::match(['get', 'post'],'/get_sizes_group', 'Admin@getSizesGroup')->middleware('Login');
Route::match(['get', 'post'],'/get_variant_group', 'Admin@getVariantGroup')->middleware('Login');

Route::match(['get', 'post'],'/sellers-payment', 'Admin\SellerController@sellersPayment')->middleware('Login');
Route::match(['get', 'post'],'/get-amount', 'Admin@GetAmount');
Route::match(['get', 'post'],'/cr-note', 'Admin\SellerController@CrNote');
Route::match(['get', 'post'],'/dr-note', 'Admin\SellerController@DrNote');
Route::match(['get', 'post'],'/seller_po', 'Admin\SellerController@SellerPo');
Route::match(['get', 'post'],'/default_image', 'Admin\FrontendController@DefaultImage');
Route::match(['get', 'post'],'/link', 'Admin\FrontendController@Link');
Route::match(['get', 'post'],'/catData', 'Admin@catData');
Route::match(['get', 'post'],'/product_sr', 'Admin\RetailController@productSr');

Route::get('/seller', 'Admin\SellerController@seller')->middleware('Login');
Route::match(['get', 'post'],'institutional', 'Admin@institutional')->middleware('Login');
Route::match(['get', 'post'],'bookings', 'Admin\InstitutionalController@bookings')->middleware('Login');
Route::match(['get', 'post'],'dispatch-programs', 'Admin\InstitutionalController@dispatchPrograms')->middleware('Login');
Route::match(['get', 'post'],'request-quotation', 'Admin\InstitutionalController@requestQuotation')->middleware('Login');
Route::match(['get', 'post'],'/sellerview', 'Admin@sellerView')->middleware('Login');
Route::get('/pendingproduct', 'Admin\SellerController@pendingproduct')->middleware('Login');
Route::get('/deleteproduct', 'Admin\SellerController@deleteproduct')->middleware('Login');
Route::get('/approvalproduct', 'Admin\SellerController@approvalproduct')->middleware('Login');
Route::get('/rejectproduct', 'Admin\SellerController@rejectproduct')->middleware('Login');
Route::match(['get', 'post'],'/match-sku', 'Admin@MatchSku');
Route::get('/myproduct', 'Admin@myProduct')->middleware('Login');
Route::get('/notice', 'Admin@notice')->middleware('Login');
Route::match(['get', 'post'],'/registerimage', 'Admin\CustomizationController@Registerimage')->middleware('Login');
Route::match(['get', 'post'],'/tmtcalculator', 'Admin\CalculatorController@Tmtcalculator')->middleware('Login');
Route::match(['get', 'post'],'/notification', 'Admin\NotificationController@Notification')->middleware('Login');
Route::match(['get', 'post'],'/retail_notification', 'Admin\NotificationController@retailNotification')->middleware('Login');
Route::match(['get', 'post'],'/request-for-call', 'Admin\InstitutionalController@requestForCall')->middleware('Login');
Route::match(['get', 'post'],'/quick-quote', 'Admin\InstitutionalController@quickQuote')->middleware('Login');
Route::match(['get', 'post'],'/mentor-program', 'Admin\InstitutionalController@mentorProgram')->middleware('Login');
Route::match(['get', 'post'],'/credit-charges', 'Admin\InstitutionalController@creditCharges')->middleware('Login');
Route::match(['get', 'post'],'/counter-offer', 'Admin\InstitutionalController@counterOffer')->middleware('Login');
Route::post('/get-customer-discount', 'Admin@getCustomerDiscount')->middleware('Login');
Route::match(['get', 'post'],'/cities', 'Admin\SettingsController@cities')->middleware('Login');
Route::match(['get', 'post'],'/get-cities-data', 'Admin@getCitiesData')->middleware('Login');

Route::post('/variantMultipleDelete', 'Admin@variantMultipleDelete')->middleware('Login');
Route::post('/get-multiple-data', 'Admin@getMultipleData')->middleware('Login');
Route::get('variantData', 'Admin@variantData')->middleware('Login');

routes/web.php
<?php
use \Illuminate\Support\Facades\Route;
Route::group(['as' => 'business.', 'prefix' => 'business'], function () {
    Route::get('/', 'Institutional\InstitutionalIndex@institutionalStatic')->name('institutionalStatic');
    Route::get('dashboard', 'Institutional@dashboard')->name('institutionalDashboard')->middleware('Institutional');
    Route::match(['get', 'post'], 'my-bookings', 'Institutional@myBookings')->name('institutionalMyBookings')->middleware('Institutional');
    Route::match(['get', 'post'], 'my-quotations', 'Institutional@myQuotations')->name('institutionalMyQuotatuins')->middleware('Institutional');
    Route::match(['get', 'post'], 'my-quotations-detail', 'Institutional@myQuotationsDetail')->name('institutionalMyQuotationDetail')->middleware('Institutional');
    Route::match(['get', 'post'], 'my-profile', 'Institutional@myProfile')->name('institutionalMyProfile')->middleware('Institutional');
    Route::get('dispatch-programs', 'Institutional@dispatchPrograms')->name('institutionalDispatchProgram')->middleware('Institutional');
    Route::get('get-dispatch-programs', 'Institutional@getDispatchPrograms')->name('institutionalGetDispatchProgram')->middleware('Institutional');
    Route::get('create-dispatch', 'Institutional@createDispatch')->name('institutionalCreateDispatch')->middleware('Institutional');
    Route::post('store-dispatch', 'Institutional@storeDispatch')->name('institutionalStoreDispatch')->middleware('Institutional');
    Route::delete('delete-dispatch', 'Institutional@deleteDispatch')->name('institutionalDeleteDispatch')->middleware('Institutional');
    Route::get('edit-dispatch', 'Institutional@editDispatch')->name('institutionalEditDispatch')->middleware('Institutional');
    Route::post('update-dispatch', 'Institutional@updateDispatch')->name('institutionalUpdateDispatch')->middleware('Institutional');
    Route::post('save-party', 'Institutional@saveParty')->name('institutionalSaveParty')->middleware('Institutional');
    Route::post('get-cities', 'Institutional@getCities')->name('institutionalGetCities')->middleware('Institutional');
    Route::post('get-variants', 'Institutional@getVariants')->name('institutionalGetVariants')->middleware('Institutional');
    Route::match(['get', 'post'],'i/index', 'Institutional\InstitutionalIndex@index')->name('institutionalIndex')->middleware('Institutional');
    Route::match(['get', 'post'], 'products/{category}/{sub?}', 'Institutional\InstitutionalProducts@products')->name('institutionalProducts')->middleware('Institutional');
    Route::post('request-quotation', 'Institutional\InstitutionalProducts@requestQuotation')->name('institutionalRequestQuotations')->middleware('Institutional');
    Route::post('rfq-request-quotation', 'Institutional\InstitutionalProducts@rfqRequestQuotation')->name('institutionalRfqRequestQuotation')->middleware('Institutional');
    Route::match(['get', 'post'],'product/{product}', 'Institutional\InstitutionalProducts@product')->name('institutionalProduct')->middleware('Institutional');
    Route::match(['get', 'post'],'check-pincode', 'Institutional\InstitutionalProducts@checkPincode')->name('institutionalCheckPincode')->middleware('Institutional');
    Route::match(['get', 'post'],'select-city', 'Institutional\InstitutionalProducts@SelectCity')->name('institutionalSelectCity')->middleware('Institutional');
    Route::post('change-hub', 'Institutional\InstitutionalIndex@changeHub')->name('institutionalChangeHub')->middleware('Institutional');
    Route::post('product-wishlist', 'Institutional\InstitutionalProducts@productWishlist')->name('institutionalProductWishlist')->middleware('Institutional');
    Route::match(['get', 'post'],'save-counter-offer', 'Institutional\InstitutionalProducts@counterOffer')->name('institutionalCounterOffer')->middleware('Institutional');
    Route::match(['get', 'post'],'get_var_price_detail', 'Institutional\InstitutionalProducts@getVarPriceDetail')->name('institutionalGetVarPriceDetail')->middleware('Institutional');
    Route::match(['get', 'post'],'rfq_booking', 'Institutional\InstitutionalProducts@rfqBooking')->name('institutionalRfqBooking')->middleware('Institutional');
    Route::get('change-password', 'Institutional\InstitutionalIndex@changePassword')->name('institutionalChangePassword')->middleware('Institutional');
    Route::get('logout', 'Institutional\InstitutionalIndex@logout')->name('institutionalLogout')->middleware('Institutional');
    Route::match(['get', 'post'],'login', 'HomeController@institutionalLogin')->name('institutionalInstitutionalLogin');
    Route::match(['get', 'post'],'/institutional/account', 'Frontend@institutionalaccount')->middleware('Customer')->name('institutionalaccount');
    Route::match(['get', 'post'],'register/{slug}', 'Frontend@register')->name('institutionalRegister');
    Route::match(['get', 'post'],'advices_cat/{category}', 'Institutional\InstitutionalProducts@advicesCat')->name('institutionalAdvicesCat')->middleware('Institutional');
    Route::match(['get', 'post'],'advices/{category}', 'Institutional\InstitutionalProducts@advices')->name('institutionalAdvices')->middleware('Institutional');
    Route::get('brand/{id}', 'Institutional\InstitutionalProducts@brand')->name('institutionalBrand')->middleware('Institutional');
    Route::post('get-products', 'Institutional\InstitutionalProducts@getProducts')->name('institutionalGetProducts')->middleware('Institutional');
    Route::get('services_category/{services_category}', 'Institutional\InstitutionalProducts@services_category')->name('institutionalServicesCategory')->middleware('Institutional');
    Route::get('design-category-layout_plans/{slug}', 'Institutional\InstitutionalProducts@layout_plans_cat')->name('institutionallayout_plans')->middleware('Institutional');
    Route::get('layout_plans/{slug}', 'Institutional\InstitutionalProducts@layout_plans');
    Route::match(['get', 'post'],'layout_plan/{slug}', 'Institutional\InstitutionalProducts@layout_plan');
    Route::get('design-category-photos/{slug}', 'Institutional\InstitutionalProducts@photos_cat')->name('institutionalphotos')->middleware('Institutional');
    Route::post('review', 'Institutional\InstitutionalProducts@review')->name('institutionalReview')->middleware('Institutional');
    Route::match(['get', 'post'],'login-model', 'HomeController@loginModal')->name('institutionalLoginModal');
    Route::match(['get', 'post'],'get-faq', 'Frontend@getFaq')->name('institutionalgetFaq')->middleware('Institutional');
    Route::post('create-project', 'Frontend@createproject')->name('institutionalCreateProject')->middleware('Institutional');
    Route::post('product-faq/', 'Frontend@productFaq')->name('institutionalProductFaq')->middleware('Institutional');
    Route::match(['get', 'post'],'reset-password/{key?}', 'Frontend@reset_password')->name('institutionalResetPassword');
    Route::post('send-asr', 'Frontend@sendAsr')->name('institutionalSendAsr')->middleware('Institutional');
    Route::post('send-rfr', 'Frontend@sendRfr')->name('institutionalSendRfr')->middleware('Institutional');
    Route::match(['get', 'post'],'account', 'Frontend@institutionalaccount')->name('institutionalAccount')->middleware('Institutional');
    Route::get('myorders', 'Institutional@myOrders')->name('institutionalMyOrders')->middleware('Institutional');
    Route::get('serviceorders', 'Frontend@institutional_serviceOrders')->name('institutionalServiceOrders')->middleware('Institutional');
    Route::get('planorders', 'Frontend@institutional_planOrders')->name('institutionalPlanOrders')->middleware('Institutional');
    Route::match(['get', 'post'],'useradvices', 'Frontend@institutional_userAdvices')->name('institutionalUserAdvices')->middleware('Institutional');


    Route::get('/contact-us', 'Frontend@institutionalContactUs')->name('institutionalContactUs');
    Route::get('/payments', 'Frontend@institutionalPayments')->name('institutionalPayments');
    Route::get('/shipping', 'Frontend@institutionalShipping')->name('institutionalShipping');
    Route::get('/cancellation', 'Frontend@institutionalCancellation')->name('institutionalCancellation');
    Route::get('/about-us', 'Frontend@institutionalAboutUs')->name('institutionalAboutUs');
    Route::get('/stories', 'Frontend@institutionalStories')->name('institutionalStories');
    Route::get('/press', 'Frontend@institutionalPress')->name('institutionalPress');
    Route::get('/sell', 'Frontend@institutionalSell')->name('institutionalSell');
    Route::get('/online-shopping', 'Frontend@institutionalOnlineShopping')->name('institutionalOnlineShopping');
    Route::get('/affiliate-program', 'Frontend@institutionalAffiliateProgram')->name('institutionalAffiliateProgram');
    Route::get('/gift-card', 'Frontend@institutionalGiftCard')->name('institutionalGiftCard');
    Route::get('/subscription', 'Frontend@institutionalSubscription')->name('institutionalSubscription');
    Route::get('/sitemap', 'Frontend@institutionalSitemap')->name('institutionalSitemap');
    Route::get('/faq', 'Frontend@institutionalFaqs')->name('institutionalFaqs');
    Route::get('/report-infringement', 'Frontend@institutionalReportInfringement')->name('institutionalReportInfringement');
    Route::get('/terms-conditions', 'Frontend@institutionalTermsConditions')->name('institutionalTermsConditions');
    Route::get('/terms-of-use', 'Frontend@institutionalTermsUse')->name('institutionalTermsUse');
    Route::post('/contact-email', 'Frontend@institutionalContactEmail')->name('institutionalContactEmail');
    Route::get('/careers', 'Frontend@institutionalCareers')->name('institutionalCareers');
    Route::get('/privacy', 'Frontend@institutionalPrivacy')->name('institutionalPrivacy');
    Route::get('/return', 'Frontend@institutionalReturn')->name('institutionalReturn');
    Route::get('/refund', 'Frontend@institutionalRefund')->name('institutionalRefund');
});

resources/views/institutional/footer.blade.php
<footer class="footer">
    <div class="d-sm-flex justify-content-center justify-content-sm-between">
        <span class="text-muted text-center text-sm-left d-block d-sm-inline-block">Copyright © 2019 <a href="https://www.aakar360.com/" target="_blank">Aakar360 Mentors Pvt Ltd</a>. All rights reserved.</span>
        <span class="float-none float-sm-right d-block mt-1 mt-sm-0 text-center">Hand-crafted & made with <i class="mdi mdi-heart text-danger"></i></span>
    </div>
</footer>
</div>
</div>
<!-- page-body-wrapper ends -->
</div>
<!-- container-scroller -->

<!-- plugins:js -->
<script src="<?=$tp;?>/vendors/base/vendor.bundle.base.js"></script>
<!-- endinject -->
<!-- Plugin js for this page-->
<script src="<?=$tp;?>/vendors/chart.js/Chart.min.js"></script>
<script src="<?=$tp; ?>/vendors/data-tables/js/jquery.dataTables.min.js" type="text/javascript"></script>
<script src="<?=$tp; ?>/vendors/data-tables/js/dataTables.select.min.js" type="text/javascript"></script>
<!-- End plugin js for this page-->
<!-- inject:js -->
<script src="<?=$tp;?>/js/off-canvas.js"></script>
<script src="<?=$tp;?>/js/hoverable-collapse.js"></script>
<script src="<?=$tp;?>/js/template.js"></script>
<!-- endinject -->
<!-- Custom js for this page-->
<script src="assets/js/select2.js"></script>
<script src="<?=$tp;?>/js/dashboard.js"></script>
<script src="<?=$tp;?>/js/bootstrap-datepicker.min.js"></script>
<script>
    $('.select2').select2({
        width: '100%'
    });
</script>
<!-- End custom js for this page-->
</body>

</html>

resources/views/institutional/header.blade.php
<!DOCTYPE html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title><?=$title;?></title>
    <!-- plugins:css -->
    <link rel="stylesheet" href="assets/css/select2.css">
    <link rel="stylesheet" href="<?=$tp;?>/vendors/mdi/css/materialdesignicons.min.css">
    <link rel="stylesheet" href="<?=$tp;?>/vendors/base/vendor.bundle.base.css">
    <!-- endinject -->
    <!-- plugin css for this page -->
    <link rel="stylesheet" href="<?=$tp;?>/vendors/datatables.net-bs4/dataTables.bootstrap4.css">
    <!-- End plugin css for this page -->
    <!-- inject:css -->
    <link rel="stylesheet" href="<?=$tp;?>/css/bootstrap-datepicker.min.css">
    <link rel="stylesheet" href="<?=$tp;?>/css/style.css">

    <!-- endinject -->
    <link rel="shortcut icon" href="<?=$tp;?>/images/favicon.png" />
</head>
<body class="sidebar-icon-only">
<div class="container-scroller">
    <!-- partial:partials/_navbar.html -->
    <nav class="navbar col-lg-12 col-12 p-0 fixed-top d-flex flex-row">
        <div class="navbar-brand-wrapper d-flex justify-content-center">
            <div class="navbar-brand-inner-wrapper d-flex justify-content-between align-items-center w-100">
                <a class="navbar-brand brand-logo" href="{{ route('business.institutionalDashboard') }}"><img src="<?=$tp;?>/images/aakar360.png" alt="logo"/></a>
                <a class="navbar-brand brand-logo-mini" href="{{ route('business.institutionalDashboard') }}"><img src="<?=$tp;?>/images/logo-mini.svg" alt="logo"/></a>
                <button class="navbar-toggler navbar-toggler align-self-center" type="button" data-toggle="minimize">
                    <span class="mdi mdi-sort-variant"></span>
                </button>
            </div>
        </div>
        <div class="navbar-menu-wrapper d-flex align-items-center justify-content-end">
            <ul class="navbar-nav navbar-nav-right">
                <li class="nav-item nav-profile dropdown">
                    <a class="nav-link dropdown-toggle" href="#" data-toggle="dropdown" id="profileDropdown">
                        <img src="<?=$tp;?>/images/faces/face5.jpg" alt="profile"/>
                        <span class="nav-profile-name"><?php $username = institutional('name'); $t = explode(' ', $username); echo $t[0]; ?></span>
                    </a>
                    <div class="dropdown-menu dropdown-menu-right navbar-dropdown" aria-labelledby="profileDropdown">
                        <a class="dropdown-item" href="{{ route('business.institutionalIndex') }}">
                            <i class="mdi mdi-web text-primary"></i>
                            Visit Website
                        </a>
                        <a class="dropdown-item" href="{{ route('business.institutionalMyProfile') }}">
                            <i class="mdi mdi-account text-primary"></i>
                            My Profile
                        </a>
                        <a class="dropdown-item" href="{{ route('business.institutionalChangePassword') }}">
                            <i class="mdi mdi-lock text-primary"></i>
                            Change Password
                        </a>
                        <a class="dropdown-item" href="{{ route('business.institutionalLogout') }}">
                            <i class="mdi mdi-logout text-primary"></i>
                            Logout
                        </a>
                    </div>
                </li>
            </ul>
            <button class="navbar-toggler navbar-toggler-right d-lg-none align-self-center" type="button" data-toggle="offcanvas">
                <span class="mdi mdi-menu"></span>
            </button>
        </div>
    </nav>
    <!-- partial -->
    <div class="container-fluid page-body-wrapper">
        <!-- partial:partials/_sidebar.html -->
        <nav class="sidebar sidebar-offcanvas" id="sidebar">
            <ul class="nav">
                <li class="nav-item">
                    <a class="nav-link" href="{{ route('business.institutionalDashboard') }}">
                        <i class="mdi mdi-home menu-icon"></i>
                        <span class="menu-title">Dashboard</span>
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" data-toggle="collapse" href="#ui-basic" aria-expanded="false" aria-controls="ui-basic">
                        <i class="mdi mdi-cart menu-icon"></i>
                        <span class="menu-title">Products</span>
                        <i class="menu-arrow"></i>
                    </a>
                    <div class="collapse" id="ui-basic">
                        <ul class="nav flex-column sub-menu">
                            <li class="nav-item"> <a class="nav-link" href="<?=route('business.institutionalMyQuotatuins')?>">My Quotations</a></li>
                            <li class="nav-item"> <a class="nav-link" href="<?=route('business.institutionalMyBookings')?>">My Bookings</a></li>
                            {{--<li class="nav-item"> <a class="nav-link" href="<?=route('business.institutionalDispatchProgram')?>">Dispatch Programs</a></li>--}}
                            {{--<li class="nav-item"> <a class="nav-link" href="<?=route('business.institutionalMyOrders')?>">My Orders</a></li>--}}
                        </ul>
                    </div>
                </li>
            </ul>
        </nav>
    <div class="main-panel">