routes/admin.php
<?php

use Illuminate\Http\Request;

/*
|--------------------------------------------------------------------------
| Admin Routes
|--------------------------------------------------------------------------
|
| Here is where you can register Admin routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| is assigned the "Admin" middleware group. Enjoy building your Admin!
|
*/

Route::match(['get', 'post'],'/login', [ 'as' => 'login', 'uses' => 'Admin@login']);
Route::get('/', 'Admin@index')->middleware('Login');
Route::get('/logout', 'Admin@logout')->middleware('Login');
Route::get('/map', 'Admin@map')->middleware('Login');
Route::match(['get', 'post'],'/products', 'Admin\ProductController@products')->middleware('Login');
Route::match(['get', 'post'],'/banners', 'Admin\FrontendController@banners')->middleware('Login');
Route::match(['get', 'post'],'/s-how-it-works', 'Admin\ServiceController@s_how_it_works')->middleware('Login');
Route::match(['get', 'post'],'/home-page-design', 'Admin\FrontendController@home_page_design')->middleware('Login');
Route::match(['get', 'post'],'/mega-menu-image', 'Admin\FrontendController@mega_menu_image')->middleware('Login');
Route::match(['get', 'post'],'/categories', 'Admin\ProductController@categories')->middleware('Login');
Route::match(['get', 'post'],'/brands', 'Admin\ProductController@brands')->middleware('Login');
Route::match(['get', 'post'],'/manufacturing-hubs', 'Admin\ProductController@manufacturingHubs')->middleware('Login');
/*Route::match(['get', 'post'],'/ph-relations', 'Admin@phRelations')->middleware('Login');*/
Route::match(['get', 'post'],'/featured', 'Admin\ProductController@featured')->middleware('Login');
Route::match(['get', 'post'],'/services_categories', 'Admin\ServiceController@services_categories')->middleware('Login');
Route::match(['get', 'post'],'/services', 'Admin\ServiceController@services')->middleware('Login');
Route::match(['get', 'post'],'/design_category', 'Admin\DesignController@design_category')->middleware('Login');
Route::match(['get', 'post'],'/layout-plans', 'Admin\DesignController@layout_plan')->middleware('Login');
Route::match(['get', 'post'],'/photos', 'Admin\DesignController@photos')->middleware('Login');
Route::match(['get', 'post'],'/update-photos', 'Admin@updatePhotos')->middleware('Login');
Route::match(['get', 'post'],'/update-questions', 'Admin@updateQuestions')->middleware('Login');
Route::match(['get', 'post'],'/questions', 'Admin@questions')->middleware('Login');
Route::match(['get', 'post'],'/category-update-questions', 'Admin@CategoryupdateQuestions')->middleware('Login');
Route::match(['get', 'post'],'/services_answer', 'Admin\ServiceController@ServicesAnswer')->middleware('Login');
Route::match(['get', 'post'],'/modify_plan', 'Admin\DesignController@modifyPlan')->middleware('Login');
Route::match(['get', 'post'],'/faq', 'Admin\ServiceController@Faq')->middleware('Login');
Route::match(['get', 'post'],'/layout_faq', 'Admin\DesignController@layoutFaq')->middleware('Login');
Route::match(['get', 'post'],'/product_faq', 'Admin\ProductController@productFaq')->middleware('Login');
Route::match(['get', 'post'],'/service_category_questions', 'Admin@Categoryquestions')->middleware('Login');
Route::match(['get', 'post'],'/service_category_image', 'Admin@Categoryimage')->middleware('Login');
Route::match(['get', 'post'],'/get_image', 'Admin@Getimage')->middleware('Login');
Route::match(['get', 'post'],'/pages', 'Admin\FrontendController@pages')->middleware('Login');
Route::match(['get', 'post'],'/blog', 'Admin\AdviceController@blog')->middleware('Login');
Route::get('/customers', 'Admin\ProductController@customers')->middleware('Login');
Route::post('/change-rfr', 'Admin@changeRfr')->middleware('Login');
Route::match(['get', 'post'],'/coupons', 'Admin\ProductController@coupons')->middleware('Login');
Route::match(['get', 'post'],'/postcodes', 'Admin\SettingsController@postcodes')->middleware('Login');
Route::match(['get', 'post'],'/shipping', 'Admin\SettingsController@shipping')->middleware('Login');
Route::match(['get', 'post'],'/flat', 'Admin\SettingsController@flat')->middleware('Login');
Route::match(['get', 'post'],'/units', 'Admin\ProductController@units')->middleware('Login');
Route::match(['get', 'post'],'/reviews', 'Admin\ProductController@reviews')->middleware('Login');
Route::match(['get', 'post'],'/photo-reviews', 'Admin\DesignController@photoreviews')->middleware('Login');
Route::match(['get', 'post'],'/layout_reviews', 'Admin\DesignController@layout_reviews')->middleware('Login');
Route::match(['get', 'post'],'/orders', 'Admin\RetailController@orders')->middleware('Login');
Route::get('/stats', 'Admin\RetailController@stats')->middleware('Login');
Route::match(['get', 'post'],'/tracking', 'Admin\MarketingController@tracking')->middleware('Login');
Route::match(['get', 'post'],'/newsletter', 'Admin\MarketingController@newsletter')->middleware('Login');
Route::get('/referrers', 'Admin\VisitorController@referrers')->middleware('Login');
Route::get('/os', 'Admin\VisitorController@os')->middleware('Login');
Route::get('/browsers', 'Admin\VisitorController@browsers')->middleware('Login');
Route::match(['get', 'post'],'/payment', 'Admin\SettingsController@payment')->middleware('Login');
Route::match(['get', 'post'],'/currency', 'Admin\SettingsController@currency')->middleware('Login');
Route::match(['get', 'post'],'/settings', 'Admin\SettingsController@settings')->middleware('Login');
Route::match(['get', 'post'],'/theme', 'Admin\SettingsController@theme')->middleware('Login');
Route::match(['get', 'post'],'/lang', 'Admin\SettingsController@lang')->middleware('Login');
Route::get('/tokens', 'Admin\SettingsController@tokens')->middleware('Login');
Route::get('/export', 'Admin\SettingsController@export')->middleware('Login');
Route::match(['get', 'post'],'/slider', 'Admin\CustomizationController@slider')->middleware('Login');
Route::match(['get', 'post'],'/editor', 'Admin\CustomizationController@editor')->middleware('Login');
Route::match(['get', 'post'],'/templates', 'Admin\CustomizationController@templates')->middleware('Login');
Route::match(['get', 'post'],'/builder', 'Admin\CustomizationController@builder')->middleware('Login');
Route::match(['get', 'post'],'/menu', 'Admin\CustomizationController@menu')->middleware('Login');
Route::match(['get', 'post'],'/bottom', 'Admin\CustomizationController@bottom')->middleware('Login');
Route::match(['get', 'post'],'/fields', 'Admin@fields')->middleware('Login');
Route::match(['get', 'post'],'/support', 'Admin\AdministrationController@support')->middleware('Login');
Route::match(['get', 'post'],'/administrators', 'Admin\AdministrationController@administrators')->middleware('Login');
Route::match(['get', 'post'],'/profile', 'Admin\AdministrationController@profile')->middleware('Login');
Route::match(['get', 'post'],'/layout_addon', 'Admin\DesignController@layout_addon')->middleware('Login');
Route::match(['get', 'post'],'/layout-plans/add-questions/{slug}', 'Admin@layout_plan_questions')->middleware('Login');
Route::match(['get', 'post'],'/layout-plans/layout_plan_addon/{slug}', 'Admin@layout_plan_addon')->middleware('Login');
Route::match(['get', 'post'],'/amminities', 'Admin\DesignController@amminities')->middleware('Login');
Route::match(['get', 'post'],'/image_likes', 'Admin\DesignController@image_likes')->middleware('Login');
Route::match(['get', 'post'],'/image_inspirations', 'Admin\DesignController@image_inspirations')->middleware('Login');
Route::match(['get', 'post'],'/plan_orders', 'Admin\DesignController@plan_orders')->middleware('Login');
Route::get('/layout-plans/delete/{slug}/{que_id}', 'Admin@layout_plan_delete_question')->middleware('Login');
Route::get('/layout-plans/delete/{slug}/{addon_id}', 'Admin@layout_plan_addoon_delete')->middleware('Login');
Route::post('/get-variant', 'Admin@getVariant')->middleware('Login');
Route::post('/get-variant-data', 'Admin@getVariantData')->middleware('Login');
Route::post('/get-discount', 'Admin@getDiscount')->middleware('Login');
Route::match(['get', 'post'],'/advices_faq', 'Admin\AdviceController@advicesFaq')->middleware('Login');
Route::match(['get', 'post'],'/advices_reviews', 'Admin\AdviceController@advices_reviews')->middleware('Login');
Route::match(['get', 'post'],'/advices_category', 'Admin\AdviceController@advices_category')->middleware('Login');
Route::match(['get', 'post'],'/best-for-cat', 'Admin\ProductController@BestForCat')->middleware('Login');
Route::match(['get', 'post'],'/services_reviews', 'Admin@services_reviews')->middleware('Login');
Route::match(['get', 'post'],'/product-type', 'Admin\ProductController@productType')->middleware('Login');
Route::match(['get', 'post'],'/filters', 'Admin\ProductController@filters')->middleware('Login');
Route::match(['get', 'post'],'/best-for-layout', 'Admin\DesignController@BestForLayout')->middleware('Login');
Route::match(['get', 'post'],'/design-cat-banner', 'Admin\DesignController@DesignCatBanner')->middleware('Login');
Route::match(['get', 'post'],'/best-for-photo', 'Admin\DesignController@BestForPhoto')->middleware('Login');
Route::match(['get', 'post'],'/length', 'Admin@Length')->middleware('Login');
Route::match(['get', 'post'],'/size', 'Admin\ProductController@Size')->middleware('Login');
Route::match(['get', 'post'],'/sizes_group', 'Admin\ProductController@SizesGroup')->middleware('Login');
Route::match(['get', 'post'],'/get_sizes_group', 'Admin@getSizesGroup')->middleware('Login');
Route::match(['get', 'post'],'/get_variant_group', 'Admin@getVariantGroup')->middleware('Login');

Route::match(['get', 'post'],'/sellers-payment', 'Admin\SellerController@sellersPayment')->middleware('Login');
Route::match(['get', 'post'],'/get-amount', 'Admin@GetAmount');
Route::match(['get', 'post'],'/cr-note', 'Admin\SellerController@CrNote');
Route::match(['get', 'post'],'/dr-note', 'Admin\SellerController@DrNote');

routes/web.php
<?php
use \Illuminate\Support\Facades\Route;
Route::group(['as' => 'business.', 'prefix' => 'business'], function () {
    Route::get('/', 'Institutional\InstitutionalIndex@institutionalStatic')->name('institutionalStatic');
    Route::get('dashboard', 'Institutional@dashboard')->name('institutionalDashboard')->middleware('Institutional');
    Route::match(['get', 'post'], 'my-bookings', 'Institutional@myBookings')->name('institutionalMyBookings')->middleware('Institutional');
    Route::match(['get', 'post'], 'my-quotations', 'Institutional@myQuotations')->name('institutionalMyQuotatuins')->middleware('Institutional');
    Route::match(['get', 'post'], 'my-quotations-detail', 'Institutional@myQuotationsDetail')->name('institutionalMyQuotationDetail')->middleware('Institutional');
    Route::match(['get', 'post'], 'my-profile', 'Institutional@myProfile')->name('institutionalMyProfile')->middleware('Institutional');
    Route::get('dispatch-programs', 'Institutional@dispatchPrograms')->name('institutionalDispatchProgram')->middleware('Institutional');
    Route::get('get-dispatch-programs', 'Institutional@getDispatchPrograms')->name('institutionalGetDispatchProgram')->middleware('Institutional');
    Route::get('create-dispatch', 'Institutional@createDispatch')->name('institutionalCreateDispatch')->middleware('Institutional');
    Route::post('store-dispatch', 'Institutional@storeDispatch')->name('institutionalStoreDispatch')->middleware('Institutional');
    Route::delete('delete-dispatch', 'Institutional@deleteDispatch')->name('institutionalDeleteDispatch')->middleware('Institutional');
    Route::get('edit-dispatch', 'Institutional@editDispatch')->name('institutionalEditDispatch')->middleware('Institutional');
    Route::post('update-dispatch', 'Institutional@updateDispatch')->name('institutionalUpdateDispatch')->middleware('Institutional');
    Route::post('save-party', 'Institutional@saveParty')->name('institutionalSaveParty')->middleware('Institutional');
    Route::post('get-cities', 'Institutional@getCities')->name('institutionalGetCities')->middleware('Institutional');
    Route::post('get-variants', 'Institutional@getVariants')->name('institutionalGetVariants')->middleware('Institutional');
    Route::match(['get', 'post'],'i/index', 'Institutional\InstitutionalIndex@index')->name('institutionalIndex')->middleware('Institutional');
    Route::match(['get', 'post'], 'products/{category}/{sub?}', 'Institutional\InstitutionalProducts@products')->name('institutionalProducts')->middleware('Institutional');
    Route::post('request-quotation', 'Institutional\InstitutionalProducts@requestQuotation')->name('institutionalRequestQuotations')->middleware('Institutional');
    Route::post('rfq-request-quotation', 'Institutional\InstitutionalProducts@rfqRequestQuotation')->name('institutionalRfqRequestQuotation')->middleware('Institutional');
    Route::match(['get', 'post'],'product/{product}', 'Institutional\InstitutionalProducts@product')->name('institutionalProduct')->middleware('Institutional');
    Route::match(['get', 'post'],'check-pincode', 'Institutional\InstitutionalProducts@checkPincode')->name('institutionalCheckPincode')->middleware('Institutional');
    Route::match(['get', 'post'],'select-city', 'Institutional\InstitutionalProducts@SelectCity')->name('institutionalSelectCity')->middleware('Institutional');
    Route::post('change-hub', 'Institutional\InstitutionalIndex@changeHub')->name('institutionalChangeHub')->middleware('Institutional');
    Route::post('product-wishlist', 'Institutional\InstitutionalProducts@productWishlist')->name('institutionalProductWishlist')->middleware('Institutional');
    Route::match(['get', 'post'],'save-counter-offer', 'Institutional\InstitutionalProducts@counterOffer')->name('institutionalCounterOffer')->middleware('Institutional');
    Route::match(['get', 'post'],'get_var_price_detail', 'Institutional\InstitutionalProducts@getVarPriceDetail')->name('institutionalGetVarPriceDetail')->middleware('Institutional');
    Route::match(['get', 'post'],'rfq_booking', 'Institutional\InstitutionalProducts@rfqBooking')->name('institutionalRfqBooking')->middleware('Institutional');
    Route::get('change-password', 'Institutional\InstitutionalIndex@changePassword')->name('institutionalChangePassword')->middleware('Institutional');
    Route::get('logout', 'Institutional\InstitutionalIndex@logout')->name('institutionalLogout')->middleware('Institutional');
    Route::match(['get', 'post'],'login', 'HomeController@institutionalLogin')->name('institutionalInstitutionalLogin');
    Route::match(['get', 'post'],'/institutional/account', 'Frontend@institutionalaccount')->middleware('Customer')->name('institutionalaccount');
    Route::match(['get', 'post'],'register/{slug}', 'Frontend@register')->name('institutionalRegister');
    Route::match(['get', 'post'],'advices_cat/{category}', 'Institutional\InstitutionalProducts@advicesCat')->name('institutionalAdvicesCat')->middleware('Institutional');
    Route::match(['get', 'post'],'advices/{category}', 'Institutional\InstitutionalProducts@advices')->name('institutionalAdvices')->middleware('Institutional');
    Route::get('brand/{id}', 'Institutional\InstitutionalProducts@brand')->name('institutionalBrand')->middleware('Institutional');
    Route::post('get-products', 'Institutional\InstitutionalProducts@getProducts')->name('institutionalGetProducts')->middleware('Institutional');
    Route::get('services_category/{services_category}', 'Institutional\InstitutionalProducts@services_category')->name('institutionalServicesCategory')->middleware('Institutional');
    Route::get('design-category-layout_plans/{slug}', 'Institutional\InstitutionalProducts@layout_plans_cat')->name('institutionallayout_plans')->middleware('Institutional');
    Route::get('layout_plans/{slug}', 'Institutional\InstitutionalProducts@layout_plans');
    Route::match(['get', 'post'],'layout_plan/{slug}', 'Institutional\InstitutionalProducts@layout_plan');
    Route::get('design-category-photos/{slug}', 'Institutional\InstitutionalProducts@photos_cat')->name('institutionalphotos')->middleware('Institutional');
    Route::post('review', 'Institutional\InstitutionalProducts@review')->name('institutionalReview')->middleware('Institutional');
    Route::match(['get', 'post'],'login-model', 'HomeController@loginModal')->name('institutionalLoginModal');
    Route::match(['get', 'post'],'get-faq', 'Frontend@getFaq')->name('institutionalgetFaq')->middleware('Institutional');
    Route::post('create-project', 'Frontend@createproject')->name('institutionalCreateProject')->middleware('Institutional');
    Route::post('product-faq/', 'Frontend@productFaq')->name('institutionalProductFaq')->middleware('Institutional');
    Route::match(['get', 'post'],'reset-password/{key?}', 'Frontend@reset_password')->name('institutionalResetPassword');
    Route::post('send-asr', 'Frontend@sendAsr')->name('institutionalSendAsr')->middleware('Institutional');
    Route::post('send-rfr', 'Frontend@sendRfr')->name('institutionalSendRfr')->middleware('Institutional');
    Route::match(['get', 'post'],'account', 'Frontend@institutionalaccount')->name('institutionalAccount')->middleware('Institutional');
    Route::get('myorders', 'Institutional@myOrders')->name('institutionalMyOrders')->middleware('Institutional');
    Route::get('serviceorders', 'Frontend@institutional_serviceOrders')->name('institutionalServiceOrders')->middleware('Institutional');
    Route::get('planorders', 'Frontend@institutional_planOrders')->name('institutionalPlanOrders')->middleware('Institutional');
    Route::match(['get', 'post'],'useradvices', 'Frontend@institutional_userAdvices')->name('institutionalUserAdvices')->middleware('Institutional');


    Route::get('/contact-us', 'Frontend@institutionalContactUs')->name('institutionalContactUs');
    Route::get('/payments', 'Frontend@institutionalPayments')->name('institutionalPayments');
    Route::get('/shipping', 'Frontend@institutionalShipping')->name('institutionalShipping');
    Route::get('/cancellation', 'Frontend@institutionalCancellation')->name('institutionalCancellation');
    Route::get('/about-us', 'Frontend@institutionalAboutUs')->name('institutionalAboutUs');
    Route::get('/stories', 'Frontend@institutionalStories')->name('institutionalStories');
    Route::get('/press', 'Frontend@institutionalPress')->name('institutionalPress');
    Route::get('/sell', 'Frontend@institutionalSell')->name('institutionalSell');
    Route::get('/online-shopping', 'Frontend@institutionalOnlineShopping')->name('institutionalOnlineShopping');
    Route::get('/affiliate-program', 'Frontend@institutionalAffiliateProgram')->name('institutionalAffiliateProgram');
    Route::get('/gift-card', 'Frontend@institutionalGiftCard')->name('institutionalGiftCard');
    Route::get('/subscription', 'Frontend@institutionalSubscription')->name('institutionalSubscription');
    Route::get('/sitemap', 'Frontend@institutionalSitemap')->name('institutionalSitemap');
    Route::get('/faq', 'Frontend@institutionalFaqs')->name('institutionalFaqs');
    Route::get('/report-infringement', 'Frontend@institutionalReportInfringement')->name('institutionalReportInfringement');
    Route::get('/terms-conditions', 'Frontend@institutionalTermsConditions')->name('institutionalTermsConditions');
    Route::get('/terms-of-use', 'Frontend@institutionalTermsUse')->name('institutionalTermsUse');
    Route::post('/contact-email', 'Frontend@institutionalContactEmail')->name('institutionalContactEmail');
    Route::get('/careers', 'Frontend@institutionalCareers')->name('institutionalCareers');
    Route::get('/privacy', 'Frontend@institutionalPrivacy')->name('institutionalPrivacy');
    Route::get('/return', 'Frontend@institutionalReturn')->name('institutionalReturn');
    Route::get('/refund', 'Frontend@institutionalRefund')->name('institutionalRefund');
});

resources/views/frontInstitutional/affiliate-program.blade.php
<?php echo $header?>
    <section class="at-contact-sec" style="background: white;">
        <div class="container">
            <div class="row">

            </div>
        </div>
    </section>
<?php echo $footer?>

resources/views/frontInstitutional/contact-us.blade.php
<?php echo $header?>
    <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3719.519146883229!2d81.6623744147666!3d21.21125268589984!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3a28dd82a50567f7%3A0xfd0d78d8d6176b27!2sAdroweb+IT+Services+Pvt.+Ltd.!5e0!3m2!1sen!2sin!4v1553672035845" width="100%" height="400" frameborder="0" style="border:0; margin-bottom: 0;" allowfullscreen></iframe>
    <section class="at-contact-sec" style="background: white;">
        <div class="container">
            <div class="row">
                <div class="col-md-6 col-sm-6">
                    <div class="at-contact-form at-col-default-mar">
                        <div id="form-messages"></div>
                        <form method="post" action="<?php url("contact-email"); ?>">
                            <?=csrf_field()?>
                            <div class="form-group">
                                <input type="text" class="form-control" name="name" placeholder="Your Name" required>
                            </div>
                            <div class="form-group">
                                <input type="text" class="form-control" name="email" placeholder="Email" required>
                            </div>
                            <div class="form-group">
                                <input type="text" class="form-control" name="subject" placeholder="Subject" required>
                            </div>
                            <div class="form-group">
                                <textarea class="form-control" name="message" rows="5" placeholder="Message" required></textarea>
                            </div>
                            <div class="form-group">
                                <button class="btn btn-default hvr-bounce-to-right" name="submit" type="submit">Sent Message</button>
                            </div>
                        </form>
                    </div>
                </div>
                <div class="col-md-6 col-sm-6">
                    <div class="at-info-box at-col-default-mar">
                        <i class="fa fa-envelope-o" aria-hidden="true"></i>
                        <p>mailaddress@gmail.com</p>
                    </div>
                    <div class="at-info-box at-col-default-mar">
                        <i class="fa fa-phone" aria-hidden="true"></i>
                        <p>+0123 (123) 6719900</p>
                    </div>
                    <div class="at-info-box at-col-default-mar">
                        <i class="fa fa-map-marker" aria-hidden="true"></i>
                        <p>99, Big Building, Glasgow, United Kingdom.</p>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!--  Contact end-->

    <script type="text/javascript" src="assets/js/google-map.js"></script>
    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDdEPAHqgxFK5pioDAB3rsvKchAtXxRGO4&amp;callback=myMap"></script>
<?php echo $footer?>

resources/views/frontInstitutional/gift-card.blade.php
<?php echo $header?>
    <section class="at-contact-sec" style="background: white;">
        <div class="container">
            <div class="row">

            </div>
        </div>
    </section>
<?php echo $footer?>

resources/views/frontInstitutional/login.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><?=$data['title'] ?></title>
    <meta name="viewport" content="initial-scale = 1.0,maximum-scale = 1.0" />
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta content='<?=$data['desc'] ?>' name='description'/>
    <meta content='<?=$data['keywords'] ?>' name='keywords'/>
    <base href="<?=url('') ?>/" />
    <link rel="shortcut icon" href="<?=url('') ?>/favicon.ico" type="image/x-icon">
    <link rel="stylesheet" type="text/css" href="<?=$data['tp'] ?>/assets/bootstrap.min.css">
    <link rel="stylesheet" type="text/css" href="<?=$data['tp'] ?>/assets/fontawesome-all.min.css">
    <link rel="stylesheet" type="text/css" href="<?=$data['tp'] ?>/assets/iofrm-style.css">
    <link rel="stylesheet" type="text/css" href="<?=$data['tp'] ?>/assets/iofrm-theme3.css">
    <style>
        .medium-password {
            color: #b7d60a;
        }

        .weak-password {
            color: #ce1d14;

        }

        .strong-password {
            color: #12CC1A;
        }
    </style>
</head>
<body>
<div class="form-body">
    <div class="row">
        <div class="img-holder" style="background-image: url('<?=$data['tp'] ?>/assets/img2.jpg')">
            <div class="bg"></div>
            <div class="info-holder">
            </div>
        </div>
        <div class="form-holder">
            <div class="form-content" style="height:100vh;">
                <div class="form-items">
                    <div class="website-logo">
                        <a href="<?=url('')?>">
                            <div class="logo">
                                <img class="logo-size" src="<?=$data['cfg']->logo ?>" alt="">
                            </div>
                        </a>
                    </div>
                    <h3>Get more things done with Loggin platform.</h3>
                    <p>Access to the most powerfull tool in the entire design and web industry.</p>
                    <?php
                    if (isset($error) && !empty($error)){
                        echo '<div class="alert alert-warning">'.translate($error).'</div>';
                    }
                    ?>
                    <form action="" method="post">
                        <?=csrf_field() ?>
                        <input tabindex="1" data-dependency="first" name="email" type="email" value="<?=isset($_POST['email']) ? $_POST['email'] : '' ?>" class="form-control" placeholder="E-mail Address" required  />
                        <input tabindex="2" class="form-control" type="password" id="password" name="password" onkeyup="checkPasswordStrength();" placeholder="Password" required>
                        <span id="password-strength-status"></span>
                        <div class="form-button">
                            <button id="submit" name="login" type="submit" class="ibtn" tab-index="3">Login</button> <a href="<?=route('business.institutionalResetPassword')?>">Forget password?</a>
                            OR <a href="{{ route('business.institutionalRegister',['institutional']) }}">Register with us!</a>
                        </div>
                    </form>
                    <!--div class="other-links">
                        <span>Or login with</span>
                            <a href="#"><i class="fab fa-facebook-f"></i></a><a href="#"><i class="fab fa-google"></i></a><a href="#"><i class="fab fa-linkedin-in"></i></a>
                    </div-->
                </div>
            </div>
        </div>
    </div>
</div>
<script src="<?=$data['tp'] ?>/assets/jquery.min.js"></script>
<script src="<?=$data['tp'] ?>/assets/main.js"></script>
</body>

</html>

resources/views/frontInstitutional/sell.blade.php
<?php echo $header?>
    <section class="at-contact-sec" style="background: white;">
        <div class="container">
            <div class="row">

            </div>
        </div>
    </section>
<?php echo $footer?>